version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    networks:
      - main-network
    ports:
      - 80:80
      - 443:443
    volumes:
            - ./config:/etc/nginx/conf.d
networks:
  main-network:
    external: true